@ECHO OFF
TITLE VIRUS ALERT
ECHO ##     ## #### ########  ##     ##  ######  
ECHO ##     ##  ##  ##     ## ##     ## ##    ## 
ECHO ##     ##  ##  ##     ## ##     ## ##       
ECHO ##     ##  ##  ########  ##     ##  ######  
ECHO  ##   ##   ##  ##   ##   ##     ##       ## 
ECHO   ## ##    ##  ##    ##  ##     ## ##    ## 
ECHO    ###    #### ##     ##  #######   ###### 
ECHO.
ECHO    ###    ##       ######## ########  ######## 
ECHO   ## ##   ##       ##       ##     ##    ##    
ECHO  ##   ##  ##       ##       ##     ##    ##    
ECHO ##     ## ##       ######   ########     ##    
ECHO ######### ##       ##       ##   ##      ##    
ECHO ##     ## ##       ##       ##    ##     ##    
ECHO ##     ## ######## ######## ##     ##    ##   
PAUSE
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
title Gathering data
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
PING www.trojan-virus.com -n 1
ping 1.1.1.1 -m 100 >NUL
cls
title ALERT
echo VIRUS HAS PROGRESSED TO C:/ DRIVE!
ping 1.1.1.1 -m 10000 >NUL
echo FILES IN C:/ WILL BE DELETED!
ping 1.1.1.1-m 10000 >NUL
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
echo PRESS ANY KEY TO PREVENT FILE DELETION!
ping 1.1.1.1 -n 1 -m 5000000000 >NUL
echo FILES IN C:/ DRIVE ARE BEING DELETED!
ping 1.1.1.1 -m 10000 >NUL
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
dir/s
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT
START VIRUSPOPS.BAT

dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s
dir/s

ping 1.1.1.1 -n 10 -m 30 <NUL

start iexplore  -k http://new.music.yahoo.com/weird-al-yankovic/videos/view/white-nerdy--35881672 >NUL
START iexplore -private -k http://www.bluescreenprank.com/blue.html
CALL finaljoke.bat
