@echo OFF
cls
echo   ,ad8888ba,   88888888ba          db         888888888888  8b        d8  
PING -w 1 >NUL
echo  d8"'    `"8b  88      "8b        d88b                 ,88   Y8,    ,8P 
PING 1.1.1.1 -n 1 -w 1 >NUL  
echo d8'            88      ,8P       d8'`8b              ,88"     Y8,  ,8P    
PING 1.1.1.1 -n 1 -w 1 >NUL
echo 88             88aaaaaa8P'      d8'  `8b           ,88"        "8aa8"     
PING 1.1.1.1 -n 1 -w 1 >NUL
echo 88             88""""88'       d8YaaaaY8b        ,88"           `88'      
PING 1.1.1.1 -n 1 -w 1 >NUL
echo Y8,            88    `8b      d8""""""""8b     ,88"              88       
PING 1.1.1.1 -n 1 -w 1 >NUL
echo  Y8a.    .a8P  88     `8b    d8'        `8b   88"                88       
PING 1.1.1.1 -n 1 -w 1 >NUL
echo   `"Y8888Y"'   88      `8b  d8'          `8b  888888888888       88   
ECHO LAWL
ECHO YOU CAN CLOSE THIS
:loop
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 70
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 07
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 70
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 07
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 70
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 07
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 70
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 07
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 70
PING 1.1.1.1 -n 1 -w 1 >NUL
COLOR 07
goto loop



